let dados = [
    {
        nome: "André Ramalho",
        descricao: "André Ramalho é um zagueiro experiente que chegou ao Corinthians com o status de reforço de peso. Com passagens por grandes clubes europeus, o defensor trouxe para o Timão sua solidez defensiva, liderança e experiência em grandes jogos. Sua chegada fortaleceu a zaga corinthiana, proporcionando mais segurança e organização à equipe. Com sua liderança natural, André Ramalho rapidamente se tornou um dos pilares do time e conquistou a confiança da Fiel Torcida.",
        insta: "https://www.instagram.com/ramalho92/",
        wiki: "https://pt.wikipedia.org/wiki/André_Ramalho",
        nacionalidade: "Brasileiro",
        idade: 32,
        camisa: 5,
        posicao: "zagueiro",
        jogos: 13,
        titulos: 0,
        gols: 1,
        assistencias: 0,
        tags: "andre",
        foto: "andre_ramalho.png",
    },

    {
        nome: "Ángel Romero",
        descricao: "Possui uma trajetória marcante no Corinthians. Sua habilidade e garra em campo o tornaram um ídolo da Fiel, contribuindo para diversos títulos e momentos históricos do clube. Com 2 passagens pelo Corinthians, Ángel Romero se destaca como o maiore artilheiro estrangeiro da história do clube, além de ser também o maior artilheiro da Neo Química Arena. Sua importância é inegável, sendo peça fundamental em diversas conquistas alvinegras.",
        insta: "https://www.instagram.com/romeroteam/",
        wiki: "https://pt.wikipedia.org/wiki/%C3%81ngel_Romero_(futebolista)",
        nacionalidade: "Paraguaio",
        idade: 32,
        camisa: 11,
        posicao: "ponta esquerda",
        jogos: 306,
        titulos: 4,
        gols: 58,
        assistencias: 24,
        tags: "angel",
        foto: "romero.png",
    },

    {
        nome: "Cacá",
        descricao: "Chegou ao Corinthians em 2024, como empréstimo, para dar mais solidez à defesa alvinegra. Sua altura e força física o tornam um defensor imponente, difícil de ser superado no jogo aéreo. Cacá se tornou um dos pilares da equipe com seu faro de gol, tanto a favor, quanto contra. Sua chegada ao Corinthians trouxe mais segurança defensiva e contribuiu em jogos importantes, conquistanto o apreço da Fiel Torcida.",
        insta: "https://www.instagram.com/cacazagueiro/",
        wiki: "https://pt.wikipedia.org/wiki/Cacá_(futebolista_de_1999)",
        nacionalidade: "Brasileiro",
        idade: 25,
        camisa: 25,
        posicao: "zagueiro",
        jogos: 31,
        titulos: 0,
        gols: 5,
        assistencias: 1,
        tags: "caca",
        foto: "caca.png",
    },

    {
        nome: "Diego Palacios",
        descricao: "Diego José Palacios Espinoza é um talentoso lateral-esquerdo equatoriano. Ele começou sua carreira no Aucas, do Equador, e teve passagens pelo Willem II, da Holanda, e pelo Los Angeles FC, dos Estados Unidos. Em 2024, Palacios foi contratado pelo Corinthians, onde rapidamente se destacou, porém se machucou logo em sua primeira partida no clube. Conhecido por sua velocidade e habilidade defensiva, ele também tem experiência internacional, tendo jogado pela seleção equatoriana na Copa do Mundo de 2022.",
        insta: "https://www.instagram.com/chiquipalacios12/",
        wiki: "https://pt.wikipedia.org/wiki/Diego_Palacios",
        nacionalidade: "Equatoriano",
        idade: 25,
        camisa: 6,
        posicao: "lateral esquerdo",
        jogos: 1,
        titulos: 0,
        gols: 0,
        assistencias: 0,
        tags: "",
        foto: "palacios.png",
    },

    {
        nome: "Félix Torres",
        descricao: "Félix Torres é um zagueiro paraguaio que se tornou peça fundamental na defesa do Corinthians. Com sua força física e bom posicionamento, o defensor rapidamente conquistou a 'confiança' da Fiel Torcida. Sua liderança em campo e experiência internacional agregam valor ao time alvinegro. Com atuações consistentes, Félix Torres se firmou como um dos pilares da defesa corinthiana, contribuindo para a solidez defensiva da equipe.",
        insta: "https://www.instagram.com/felix_torres_s_c/",
        wiki: "https://pt.wikipedia.org/wiki/Félix_Torres",
        nacionalidade: "Equatoriano",
        idade: 27,
        camisa: 3,
        posicao: "zagueiro",
        jogos: 42,
        titulos: 0,
        gols: 0,
        assistencias: 0,
        tags: "felix",
        foto: "felix.png",
    },

    {
        nome: "Gustavo Henrique",
        descricao: "Gustavo Henrique é um zagueiro experiente que chegou ao Corinthians em 2024, com o peso de sua passagem por grandes clubes como Flamengo e Santos. Sua liderança, força física e experiência em grandes jogos são fundamentais para a defesa alvinegra. Com títulos conquistados em sua carreira, o defensor traz consigo a bagagem de um vencedor. Sua chegada ao Timão fortaleceu a equipe e o tornou um dos pilares da defesa corinthiana.",
        insta: "https://www.instagram.com/ghenrique093/",
        wiki: "https://pt.wikipedia.org/wiki/Gustavo_Henrique",
        nacionalidade: "Brasileiro",
        idade: 31,
        camisa: 13,
        posicao: "zagueiro",
        jogos: 22,
        titulos: 0,
        gols: 1,
        assistencias: 0,
        tags: "gh",
        foto: "gustavo_henrique.png",
    },

    {
        nome: "Hugo",
        descricao: "Revelado no futebol alagoano, o jogador foi contratado pelo Timão em 2024. Conhecido por sua velocidade e boa capacidade de cruzamento, Hugo se destaca pela sua versatilidade, podendo atuar tanto na defesa quanto no meio-campo. Com passagens por outros clubes, o atleta chegou ao Corinthians para agregar experiência e qualidade ao elenco.",
        insta: "https://www.instagram.com/hugoffarias_/",
        wiki: "https://pt.wikipedia.org/wiki/Hugo_Ferreira",
        nacionalidade: "Brasileiro",
        idade: 27,
        camisa: 46,
        posicao: "lateral esquerdo",
        jogos: 45,
        titulos: 0,
        gols: 0,
        assistencias: 6,
        tags: "",
        foto: "hugo.png",
    },

    {
        nome: "Hugo Souza",
        descricao: "Revelação das categorias de base do Flamengo, Hugo Souza chegou ao Corinthians em 2024 por empréstimo e rapidamente se adaptou ao estilo de jogo do Timão. Sua segurança sob as traves e importantes defesas o transformaram em peça fundamental da equipe, conquistando a confiança da torcida corintiana. A chegada do jovem goleiro gerou grande expectativa, e sua performance em campo tem confirmado o potencial para se tornar um dos grandes ídolos da posição.",
        insta: "https://www.instagram.com/hugosouza/",
        wiki: "https://pt.wikipedia.org/wiki/Hugo_Souza",
        nacionalidade: "Brasileiro",
        idade: 25,
        camisa: 1,
        posicao: "goleiro",
        jogos: 14,
        titulos: 0,
        penal_def: 4,
        gols_sofri: 14,
        gols: 0,
        assistencias: 0,
        tags: "sousa",
        foto: "hugo_souza.png"
    },

    {
        nome: "Igor Coronado",
        descricao: "Com passagens por diversos clubes europeus, Igor chegou ao Corinthians com a expectativa de ser o maestro do time. Sua chegada fortaleceu o meio-campo alvinegro, proporcionando mais qualidade e criatividade ao time com sua visão de jogo, habilidade para criar jogadas e precisão nos passes. Com gols importantes e assistências precisas, Coronado se tornou um dos principais jogadores do Corinthians e impressionou a torcida com seu futebol técnico e elegante.",
        insta: "https://www.instagram.com/igor_coronado/",
        wiki: "https://pt.wikipedia.org/wiki/Igor_Coronado",
        nacionalidade: "Brasileiro",
        idade: 32,
        camisa: 77,
        posicao: "meia ofensivo",
        jogos: 28,
        titulos: 0,
        gols: 2,
        assistencias: 3,
        tags: "",
        foto: "igor_coronado.png",
    },

    {
        nome: "Léo Mana",
        descricao: "Léo Mana é um lateral-direito brasileiro, cria da base corinthiana. Revelado nas categorias de base do Timão, o jovem jogador chamou a atenção pela sua velocidade, habilidade e bom cruzamento. Campeão da Copa São Paulo de Futebol Júnior em 2024, Léo Mana se destacou como um dos líderes da equipe, demonstrando maturidade e experiência além de sua idade. Promovido ao profissional em 2023, Léo Mana já mostra seu potencial e vem se consolidando como uma das promessas da posição no futebol brasileiro. Sua trajetória nas categorias de base, marcada por conquistas e atuações consistentes, indica que o jovem talento tem tudo para se tornar um dos pilares do Corinthians nos próximos anos.",
        insta: "https://www.instagram.com/leomana/",
        wiki: "https://www.transfermarkt.com.br/leo-mana/profil/spieler/838387",
        nacionalidade: "Brasileiro",
        idade: 20,
        camisa: 35,
        posicao: "lateral direito",
        jogos: 16,
        titulos: 2,
        gols: 0,
        assistencias: 2,
        tags: "leo maná cria do terrão terrao",
        foto: "leo_mana.png",
    },
    
    {
        nome: "Matheuzinho",
        descricao: "Se destaca pela sua velocidade, habilidade e bom cruzamento. Revelado nas categorias de base, o jogador chamou a atenção pela sua versatilidade, podendo atuar tanto na defesa quanto no meio-campo. Com uma ascensão meteórica em sua carreira, Matheuzinho rapidamente se tornou um dos destaques de sua equipe. Sua capacidade de desbordar pela linha de fundo e cruzar com precisão para a área o tornam um jogador perigoso para qualquer defesa.",
        insta: "https://www.instagram.com/matheuzinhoo/",
        wiki: "https://pt.wikipedia.org/wiki/Matheuzinho",
        nacionalidade: "Brasileiro",
        idade: 24,
        camisa: 2,
        posicao: "lateral direito",
        jogos: 35,
        titulos: 0,
        gols: 1,
        assistencias: 0,
        tags: "mateuzinho matheusinho",
        foto: "matheuzinho.png",
    },

    {
        nome: "Matheus Bidu",
        descricao: "Matheus Bidu, lateral-esquerdo canhoto, rapidamente conquistou o coração da Fiel Torcida. Chegando ao Corinthians em 2022, o jogador se adaptou rapidamente ao estilo de jogo do clube e se tornou peça fundamental na equipe. Com sua velocidade, boa técnica e cruzamentos precisos, Matheus Bidu se destaca tanto na defesa quanto no ataque. Sua versatilidade permite que ele se encaixe em diferentes esquemas táticos, contribuindo para o equilíbrio do time.",
        insta: "https://www.instagram.com/_matheusbidu/",
        wiki: "https://pt.wikipedia.org/wiki/Matheus_Bidu",
        nacionalidade: "Brasileiro",
        idade: 25,
        camisa: 21,
        posicao: "lateral esquerdo",
        jogos: 55,
        titulos: 0,
        gols: 2,
        assistencias: 2,
        tags: "mateus mathéus",
        foto: "matheus_bidu.png",
    },

    {
        nome: "Matheus Donelli",
        descricao: "Matheus Donelli é uma das joias da base corinthiana. Revelado nas categorias de base, o jovem goleiro vem se destacando no profissional e já demonstra segurança e reflexos apurados. Considerado um dos maiores talentos da posição no Brasil, Donelli é visto como o futuro da meta alvinegra e tem tudo para se tornar um ídolo da Fiel Torcida.",
        insta: "https://www.instagram.com/matheusdonelli/",
        wiki: "https://pt.wikipedia.org/wiki/Matheus_Donelli",
        nacionalidade: "Brasileiro",
        idade: 22,
        camisa: 32,
        posicao: "goleiro",
        jogos: 17,
        titulos: 0,
        penal_def: 1,
        gols_sofri: 24,
        gols: 0,
        assistencias: 0,
        tags: "cria do terrão terrao mateus doneli",
        foto: "matheus_donelli.png",
    },

    {
        nome: "Raniele",
        descricao: "Chegou ao Corinthians com a expectativa de ser um dos pilares do meio-campo alvinegro. Vindo do Cuiabá em 2024, o jogador rapidamente se firmou como titular e conquistou a torcida com sua raça e entrega em campo. Sua versatilidade permite atuar tanto como volante quanto como zagueiro, agregando ainda mais valor ao elenco. Com atuações consistentes, Raniele se tornou peça fundamental no esquema tático do Corinthians.",
        insta: "https://www.instagram.com/r14niele/",
        wiki: "https://pt.wikipedia.org/wiki/Raniele",
        nacionalidade: "Brasileiro",
        idade: 27,
        camisa: 14,
        posicao: "volante",
        jogos: 46,
        titulos: 0,
        gols: 0,
        assistencias: 0,
        tags: "",
        foto: "raniele.png",
    },

    {
        nome: "Rodrigo Garro",
        descricao: " Chegando ao clube em 2024, como uma revelação do futebol argentino, o jogador rapidamente se adaptou ao futebol brasileiro e se tornou uma peça fundamental no meio-campo alvinegro. Sua visão de jogo, passes precisos e habilidade para criar jogadas o tornam um dos principais articuladores do time. Com rápida ascensão, Garro já conquistou a torcida com seu futebol técnico e elegante, sendo peça chave nos esquemas dos treinadores. Sua importância para o time é evidente, pois ele é o responsável por ditar o ritmo das partidas e criar oportunidades de gol para seus companheiros.",
        wiki: "https://pt.wikipedia.org/wiki/Rodrigo_Garro",
        insta: "https://www.instagram.com/rodrigarroo/",
        nacionalidade: "Argentino",
        idade: 26,
        camisa: 10,
        posicao: "meia ofensivo",
        jogos: 44,
        titulos: 0,
        gols: 6,
        assistencias: 5,
        tags: "",
        foto: "rodrigo_garro.png",
    },

    {
        nome: "Talles Magno",
        descricao: "Um jovem talento que despontou no futebol brasileiro defendendo as cores do Vasco da Gama. Contratado pelo New York City FC, o atacante logo foi emprestado ao Corinthians, onde rapidamente se tornou ídolo da Fiel Torcida. Sua velocidade, dribles e finalizações precisas o destacam em campo. Com passagens marcantes pela Seleção Brasileira de base, Talles Magno já acumula gols importantes com a camisa alvinegra, sendo peça fundamental nos esquemas dos treinadores.",
        insta: "https://www.instagram.com/talles_magno/",
        wiki: "https://pt.wikipedia.org/wiki/Talles_Magno",
        nacionalidade: "Brasileiro",
        idade: 22,
        camisa: 43,
        posicao: "ponta esquerdo",
        jogos: 5,
        titulos: 0,
        gols: 3,
        assistencias: 0,
        tags: "tales",
        foto: "talles_magno.png",
    },

    {
        nome: "Yuri Alberto",
        descricao: "Chegou ao Corinthians com grande expectativa. Revelado pelo Santos, ele passou pelo Internacional e teve uma experiência na Europa antes de retornar ao Brasil. Com um estilo de jogo aguerrido e habilidade para finalizar, Yuri logo se tornou peça fundamental no ataque corinthiano. Apesar de seus altos e baixos no clube, tem a admiração de parte da torcida por sua entrega em campo. Sua importância para o time é evidente, pois ele é um dos principais responsáveis por converter as chances de gol criadas pela equipe.",
        insta: "https://www.instagram.com/yurialberto/",
        wiki: "https://pt.wikipedia.org/wiki/Yuri_Alberto",
        nacionalidade: "Brasileiro",
        idade: 23,
        camisa: 9,
        posicao: "centroavante",
        jogos: 132,
        titulos: 0,
        gols: 42,
        assistencias: 13,
        tags: "",
        foto: "yuri_alberto.png",
    },



    // {
    //     nome: "Caetano",
    //     descricao: "Um 'cria do terrão' que vem se destacando no profissional. Revelado nas categorias de base, Apesar da pouca idade, o zagueiro conquistou seu espaço no time principal, por um período, com sua técnica apurada, visão de jogo e bom passe. Sua versatilidade permite atuar tanto como zagueiro central quanto como lateral esquerdo, agregando ainda mais valor ao elenco. Com grande potencial, o jovem defensor é visto como uma das 'promessas' do futebol brasileiro.",
    //     insta: "https://www.instagram.com/caetano99/",
    //     wiki: "https://www.transfermarkt.com.br/caetano/profil/spieler/625345",
    //     nacionalidade: "Brasileiro",
    //     idade: 25,
    //     camisa: 4,
    //     posicao: "zagueiro",
    //     jogos: 36,
    //     titulos: 0,
    //     gols: 0,
    //     assistencias: 0,
    //     tags: "cria do terrão terrao",
    //     foto: "caetano.png",
    // },

    // {
    //     nome: "Fagner",
    //     descricao: "Revelado nas categorias de base do Corinthians e passagens pela Seleção Brasileira, o jogador acumula passagens por outros clubes, mas sempre retorna ao Timão. Sua identificação com o clube, com sua entrega e raça, sua versatilidade e sua experiência em campo o tornam um dos pilares da equipe. Com diversos títulos conquistados, incluindo Campeonatos Brasileiros e Paulistas, Fagner é peça fundamental no esquema tático do Corinthians e um dos líderes do elenco. Sua trajetória no clube é marcada por diversos momentos memoráveis.",
    //     insta: "https://www.instagram.com/fagneroficial23/",
    //     wiki: "https://pt.wikipedia.org/wiki/Fagner_(futebolista)",
    //     nacionalidade: "Brasileiro",
    //     idade: 34,
    //     camisa: 23,
    //     posicao: "lateral direito",
    //     jogos: 571,
    //     titulos: 5,
    //     gols: 12,
    //     assistencias: 67,
    //     tags: "cria do terrão terrao",
    //     foto: "fagner.png",
    // },

];
